# Generated by Django 3.0.4 on 2020-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='height',
            field=models.FloatField(default=0),
        ),
    ]
