# Generated by Django 3.0.4 on 2020-07-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0003_auto_20200608_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='himando',
        ),
    ]
